// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  Plasmic按钮,
  Default按钮Props
} from "./plasmic/c_vevaluatesingle/Plasmic\u6309\u94AE";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface 按钮Props extends Omit<Default按钮Props, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from Default按钮Props altogether and have
// total control over the props for your component.
export interface 按钮Props extends Default按钮Props {}

function 按钮_(props: 按钮Props, ref: HTMLElementRefOf<"div">) {
  // Use Plasmic按钮 to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into Plasmic按钮 are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all 按钮Props here, but feel free
  // to do whatever works for you.

  return <Plasmic按钮 root={{ ref }} {...props} />;
}

const 按钮 = React.forwardRef(按钮_);
export default 按钮;
